### ISSUE TITLE
Fails when submitting a listed add-on

### ISSUE THREAD

**Issue by iorate** [tophat/semantic-release-firefox-add-on#88]
Version: 0.2.2
Runs on: ubuntu-latest on GitHub Actions

The publish step fails when I submit [my add-on](https://github.com/iorate/uBlacklist) to AMO. Although a new version is actually uploaded for review, the publish step fails, so the subsequent plugins are not executed.

`web-ext` seems to throw an error when submitting a listed add-on (ref. https://github.com/mozilla/web-ext/issues/804 ).

Could you please work around it? (like https://github.com/fregante/web-ext-submit ?)

Log:
```
[3:08:17 PM] [semantic-release] › ℹ  Start step "publish" of plugin "semantic-release-firefox-add-on"
Building web extension from dist/firefox/production

Validating add-on [            .                                               ]
...
Validating add-on [............................................................]
Validation results: https://addons.mozilla.org/en-US/developers/upload/********************************

Signing add-on [           .                                                   ]
Signing add-on [...............................................................]
Your add-on has been submitted for review. It passed validation but could not be automatically signed because this is a listed add-on.
FAIL
[3:08:23 PM] [semantic-release] › ✖  Failed step "publish" of plugin "semantic-release-firefox-add-on"
[3:08:23 PM] [semantic-release] › ✖  An error occurred while running semantic-release: o: The extension could not be signed
    at /home/runner/work/uBlacklist/uBlacklist/node_modules/web-ext/dist/web-ext.js:1:66345
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at publish (/home/runner/work/uBlacklist/uBlacklist/node_modules/semantic-release-firefox-add-on/src/publish.js:25:42)
    at validator (/home/runner/work/uBlacklist/uBlacklist/node_modules/semantic-release/lib/plugins/normalize.js:34:24)
    at /home/runner/work/uBlacklist/uBlacklist/node_modules/semantic-release/lib/plugins/pipeline.js:37:34
    at async Promise.all (index 0)
    at next (/home/runner/work/uBlacklist/uBlacklist/node_modules/p-reduce/index.js:16:18) {
  pluginName: 'semantic-release-firefox-add-on'
}
o: The extension could not be signed
    at /home/runner/work/uBlacklist/uBlacklist/node_modules/web-ext/dist/web-ext.js:1:66345
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at publish (/home/runner/work/uBlacklist/uBlacklist/node_modules/semantic-release-firefox-add-on/src/publish.js:25:42)
    at validator (/home/runner/work/uBlacklist/uBlacklist/node_modules/semantic-release/lib/plugins/normalize.js:34:24)
    at /home/runner/work/uBlacklist/uBlacklist/node_modules/semantic-release/lib/plugins/pipeline.js:37:34
    at async Promise.all (index 0)
    at next (/home/runner/work/uBlacklist/uBlacklist/node_modules/p-reduce/index.js:16:18) {
  pluginName: 'semantic-release-firefox-add-on'
}
##[error]Process completed with exit code 1.
```

**Comment by iamogbz** [comment]
@iorate open to PRs! We'd prefer to use the node api and not the cli interface but `fregante/web-ext-submit` does give some ideas

@dbasilio what do you think about wrapping the default add on signer used here https://github.com/mozilla/web-ext/blob/9735a1f48696cd2dce719688fc4ce9f7cb3883f2/src/cmd/sign.js#L68

```js
const defaultAddonSigner = require('sign-addon');
```

To be successful if the error is specific to this case

```js
const signAddon = async (options, extras) => {
    const result = await defaultAddonSigner(options, extras)
	if (!result.success && result.errorCode === 'ADDON_NOT_AUTO_SIGNED') {
        result.success = true
		result.downloadedFiles = result.downloadedFiles || []
    }
    return result
}
```

And then update here https://github.com/tophat/semantic-release-firefox-add-on/blob/202cbfa092499887f0c08b1a9f915557c8f95221/src/publish.js#L25-L32 to

```js
const { success, downloadedFiles } = await webExt.cmd.sign({...}, { signAddon })
```

And account for the case where there is no downloaded file somehow here https://github.com/tophat/semantic-release-firefox-add-on/blob/202cbfa092499887f0c08b1a9f915557c8f95221/src/publish.js#L38-L42 and any other places?

**Comment by iorate** [comment]
How about saving an unsigned file created by `webExt.cmd.build` when there is no downloaded file?
https://github.com/iorate/semantic-release-firefox-add-on/commit/d9e68d11cd7d468867e9cfb0ab686e1a1d676b69

**Comment by iamogbz** [comment]
@iorate you can put up a PR, but I don't think we need the additional build step since the sign command should build the file as well

**Comment by iorate** [comment]
@iamogbz An "additional" build step is not required to save an unsigned file. `webExt.cmd.sign` calls `build` internally by default, and we can override it only to extract the path of the built file.

```javascript
let unsignedZipPath
const build = async (params, options) => {
    const result = await webExt.cmd.build(params, options)
    unsignedZipPath = result.extensionPath
    return result
}
// ...
const { success, downloadedFiles } = await webExt.cmd.sign(
    // ...
    {
        build,
        signAddon,
    },
)
```

**Comment by iamogbz** [comment]
@iorate nice feel free to put up a PR! Also the `extensionPath` is passed as an arg to the `signAddon` function so we do no need to wrap the `build` function.

We could modify the example above to include extracting the unsigned extension

```js
let unsignedXpiPath
const signAddon = async (options, extras) => {
	unsignedXpiPath = options.xpiPath
    const result = await defaultAddonSigner(options, extras)
	if (!result.success && result.errorCode === 'ADDON_NOT_AUTO_SIGNED') {
        result.success = true
		result.downloadedFiles = result.downloadedFiles || []
    }
    return result
}
```
